os: osx
osx_image: xcode9.4

language: node_js
node_js:
  - lts/*
cache:
  directories:
    - "node_modules"

before_install:
  - npm install -g greenkeeper-lockfile

before_script:
  - swiftlint version
  - greenkeeper-lockfile-update

script:
  - npm run lint

after_script:
  - greenkeeper-lockfile-upload
