name: Linting

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3.6.0
        with:
          node-version: '12.x'

      - name: Environment Information
        run: |
          node --version
          npm --version

      - name: Setup
        run: |
          swiftlint version
          npm ci

      - name: Linting
        run: npm run lint
