name: Security

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.6.0

      - uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - name: Environment Information
        run: |
          node --version
          npm --version

      - run: npm audit
